### ISSUE TITLE
WeldsModel restrict to a specific database.

### ISSUE THREAD

**Issue by ronniec95** [weldsorm/welds#124]
If I use an enums as one of the fields it works fine as long as I'm using postgres, but if I enable mssql then it complains ToSql trait hasn't been implemented.

I'm not using this specific WeldsModel for mssql so it shouldn't matter. Is there a way to restrict a model to a specific database?

**Comment by lex148** [comment]
Good morning @ronniec95 

So unfortunately not. This would be a bit difficult to do. This is do to the underlying connection needing to be able to support all types that could be send over it regardless of the model. I will take a look to see what would be possible. In the meantime I would recommend just supporting your Enum in mssql. Its pretty simple to support your own types with Tiberius. If you don't care if it actually works with mssql its even easier :) 

Something like this should do the trick.

```rust
use welds::prelude::*;
use welds_connections::row::TiberiusDecode;

#[derive(Debug, WeldsModel, PartialEq)]
#[welds(table = "dogs")]
pub(crate) struct Dog {
    #[welds(primary_key)]
    pub(crate) id: uuid::Uuid,
    pub(crate) name: String,
    pub(crate) wags: i32,
    pub(crate) breed: Breed,
}

#[derive(Debug, PartialEq, Default, Clone, Copy, sqlx::Type)]
#[sqlx(type_name = "dog_breed", rename_all = "lowercase")]
pub enum Breed {
    Terrier,
    #[default]
    GoldenRetriever,
    LabradorRetriever,
    GreatDane,
    Chihuahua,
}

impl tiberius::ToSql for Breed {
    fn to_sql(&self) -> tiberius::ColumnData<'_> {
        todo!()
    }
}

impl TiberiusDecode for Breed {
    fn read(
        _col: &tiberius::Column,
        _value: tiberius::ColumnData<'static>,
    ) -> welds_connections::errors::Result<Self> {
        todo!()
    }
}
```

I just pushed a change to make TiberiusDecode public. If you want to use this you will need to point welds and welds-connection to git main. Here is the Cargo.toml file I used for this example.

```toml
[package]
name = "typetest"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dotenvy = "0.15.7"
log = "0.4.27"
pretty_env_logger = "0.5.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-rustls", "uuid", "chrono"] }
tiberius = "0.12.3"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
welds = { git="https://github.com/weldsorm/welds.git", features = ["migrations", "postgres", "mssql"] }
welds-connections = { git="https://github.com/weldsorm/welds.git" }

```
