### ISSUE TITLE
How can I get decimal feild value in mssql?

### ISSUE THREAD

**Issue by taoqf** [weldsorm/welds#47]
table
```rs
type DECIMAL = f64;  // I munally add this type here after welds-cli generate

use welds::WeldsModel;

#[derive(Debug, WeldsModel)]
#[welds(schema = "dbo", table = "a")]
pub struct A {
	#[welds(rename = "f1")]
	pub f_1: String,
	#[welds(rename = "f2")]
	pub f_2: DECIMAL,
}
```

and this is my test

```rs

#[tokio::test]
async fn test() {
	let client = super::super::conn::getconn().await;

	let mut data = A::all()
		.select(|r| r.f_1)
		.select(|r| r.f_2)
		.where_col(|r| r.f_1.equal("foo"))
		.limit(1)
		.run(&client)
		.await
		.unwrap();

	assert!(data.is_empty() == false);

	#[derive(Debug)]
	struct View {
		foo: String,
		bar: DECIMAL,
	}
	let data: Vec<View> = data
		.drain(..)
		.map(|r| {
			let v = r.get::<DECIMAL>("f_2");

			let bar = match v {
				Ok(v) => {
					log::debug!("ok:bar is {}", v);
					v
				}
				Err(e) => {
					log::debug!("err {}", e);
					log::error!("{:#?}", e);
					0_f64
				}
			};
			log::debug!("bar==={}", bar);
			View {
				foo: r.get("foo").unwrap(),
				bar,
			}
		})
		.collect();
	dbg!(data);
}
```

when I run the test, I got this:

```log
2025-01-10T04:06:09.678781107+00:00 [src/db/test/a/definition.rs:54] ERROR dfactory01::db::test::a::definition:Tiberius(
    Conversion(
        "cannot interpret Numeric(Some(123.0)) as an f64 value",
    ),
)
```

How can I define DECIMAL?

**Comment by lex148** [comment]
good question. I will work on the documentation to make this a little clearer. Time, UUIDs, Decimal all come from external crates. these are really dependent on the underlying driver. for mssql (tiberius) You need to do a little more enabling of features in the Cargo.toml file.

```toml
[package]
name = "show"
version = "0.1.0"
edition = "2021"

[dependencies]
welds = { version = "0.4", features = ["mssql"] }
tokio = { version = "1.41", features = ["full"] }
welds-connections = { version = "0.4.10", features = ["mssql", "mssql-rust_decimal"] }
tiberius = { version = "0.12.3", features = ["rust_decimal"] }
```

```rust
use tiberius::numeric::Decimal;
use welds::prelude::*;

#[derive(Debug, WeldsModel)]
#[welds(table = "things")]
pub struct Thing {
    #[welds(primary_key)]
    pub id: i64,
    pub af2: Decimal,
}
```

**Comment by taoqf** [comment]
Thanks.

**Comment by taoqf** [comment]
```toml
welds = { version = "0.4", features = ["mssql"] }
welds-connections = { version = "0.4.10", features = ["mssql", "mssql-rust_decimal"] }
```

I am a new ruster, and I could not tell the features. if use this config above, I cannot connect to another postgres db.
when I use "full"(or ["full", "mssql"], ["postgres", "mssql"]), I got this error:

```log
error[E0277]: the trait bound `Decimal: row::mssql_row_wrapper::TiberiusDecode` is not satisfied
   --> src/db/test/a/definition.rs:16:17
    |
16  | #[derive(Debug, WeldsModel)]
    |                 ^^^^^^^^^^ the trait `row::mssql_row_wrapper::TiberiusDecode` is not implemented for `Decimal`
    |
    = help: the following other types implement trait `row::mssql_row_wrapper::TiberiusDecode`:
              Vec<u8>
              XmlData
              bool
              f32
              f64
              i16
              i32
              i64
            and 5 others
```

this is my entire cargo.toml

```toml
[package]
name = "myprj"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
dotenvy = "0.15.7"
log = "0.4.22"
log4rs = "1.3.0"
bb8 = "0.8"
bb8-tiberius = "0.15"
chrono = "0.4.39"
urlencoding = "2.1.3"
serde_json = "1.0"
# sea-orm = "1.1.3"
# canyon_sql = "0.5.1"
# rust_decimal = "1.36.0"
# diesel = { version = "2.2.6", features = ["postgres"] }

[dependencies.tokio]
version = "1.42.0"
features = ["full"]

[dependencies.tiberius]
version = "0.12.3"
features = ["rust_decimal"]

[dependencies.reqwest]
version = "0.12.12"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sqlx]
version = "0.8.3"
features = ["chrono", "runtime-async-std"]

[dependencies.welds]
version = "0.4.10"
features = ["full"]

[dependencies.welds-connections]
version = "0.4.10"
features = ["full"]

[dependencies.uuid]
version = "1.11.0"
features = [
	"v4",                # Lets you generate random UUIDs
	"fast-rng",          # Use a faster (but still sufficiently random) RNG
	"macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
```

**Comment by lex148** [comment]
There is a trade off that you are running into. when you enable everything "full" you are saying you want to compile with ALL database drivers. This is fine if that is what you need to support, but this comes at a cost. you limit yourself to rust types that are supported under all database drivers. I don't think the sqlite driver supports Decimal. 

It sounds like you need decimal types for mssql and postgres. 
Note: This is a decimal type NOT a floating point number. floats should work everywhere out of the box. 

If that is what you are looking for try something like this.

```toml
[package]
name = "show"
version = "0.1.0"
edition = "2021"

[dependencies]
welds = { version = "0.4", features = ["mssql", "postgres"] }
tokio = { version = "1.41", features = ["full"] }
welds-connections = { version = "0.4.10", features = ["mssql", "mssql-rust_decimal"] }
tiberius = { version = "0.12.3", features = ["rust_decimal"] }
rust_decimal = "1.36.0"
sqlx = { version = "0.8.3", features = ["rust_decimal"] }
```

```rust
use rust_decimal::Decimal;
use welds::prelude::*;

#[derive(Debug, WeldsModel)]
#[welds(table = "things")]
pub struct Thing {
    #[welds(primary_key)]
    pub id: i64,
    pub af2: Decimal,
}

#[tokio::main]
async fn main() -> welds::errors::Result<()> {
    // This could be a Postgres connection string OR mssql connection string
    // see welds_connections for example connection_strings
    let connection_string = std::env::var("DATABASE_URL").unwrap();
    let db = welds::connections::connect(connection_string).await?;

    let all = Thing::all().run(db.as_ref()).await?;

    for thing in all {
        println!("Thing {:?}", thing);
    }

    Ok(())
}
```



One more problem you might be running into soon. try not to mix and match async runtimes. I don't think "runtime-async-std" and "tokio" work together.
